### ISSUE TITLE
use jsonpath in place of keys

### ISSUE THREAD

**Issue by bartsimp** [qntfy/jsonparser#8]
Why do you perform the lookup using array of keys 

`jsonparser.Get(data, "person", "name", "fullName")`

and not a jsonpath notation? 

`jsonparser.Get(data, "$.person.name.fullName")`

**Comment by JoshuaC215** [comment]
Hi there! You might want to direct this question to https://github.com/buger/jsonparser

This is a fork that is being minimally monitored / maintained. The design decision you mentioned was made in the original repo long before this fork existed :)
